services:
  web:
    build: .
    container_name: agro_data 
    ports:
      - "5000:5000"
    volumes:
      - ./:/app # Monto todo el proyecto  

    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1 # Fuerza modo debug con autoreload
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/agro_data
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: agro_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
